config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resources :questions, only: [:index, :new, :edit, :create]
  # resources :questions, only: %i[index new edit create update destroy show]
  # get "/questions", to: "questions#index"
  # get "/questions/new", to: "questions#new"
  # post "/questions", to: "questions#create"
  # get "/questions/:id/edit", to: "questions#edit"

  resource :session, only: %i[new create destroy]
  resources :users, only: %i[index new create edit update destroy]
  resources :customers, only: %i[index new create edit update destroy]

  resources :tool_categories do
    resources :tool_lists
  end

  resources :tool_lists do
    resources :tool_numbers
  end

  # scope 'tool', as: 'tool' do
  #   resources :tool_categories, as: 'category', path: 'category' do
  #     resources :tool_lists, as: 'list', path: 'list' do
  #       resources :tool_numbers, as: 'number', path: 'number'
  #     end
  #   end
  # end

  get '/tool_lists/preview', to: 'tool_lists#preview'

  resources :questions do
    # resources :answers, only: %i[create destroy edit update]
    resources :answers, except: %i[new show]
  end

  root 'pages#index'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :answers, dependent: :destroy

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :set_question!, only: %i[show edit update destroy]

  def index
    @pagy, @questions = pagy(Question.order(created_at: :desc), items: 12)
    @questions = @questions.decorate
    # @questions = Question.order(created_at: :desc).page params[:page] -This was used for kaminari
  end

  def show
    @question = @question.decorate
    @answer = @question.answers.build
    @pagy, @answers = pagy(@question.answers.order(created_at: :desc), items: 8)
    @answers = @answers.decorate
    # @answers = @question.answers.order(created_at: :desc).page(params[:page]).per(2) -This was used for kaminari
    # @answers = Answer.where(question_id: @question.id).order created_at: :desc
    # @answers = Answer.where(question: @question).order created_at: :desc
  end

  def new
    @question = Question.new
  end

  def edit; end

  def create
    @question = Question.new question_params
    if @question.save
      flash[:success] = t(:question_created)
      redirect_to questions_path
    else
      flash[:error] = t(:error)
      redirect_to :new
    end
  end

  def update
    if @question.update question_params
      flash[:success] = t(:question_updated)
      redirect_to questions_path
    else
      flash[:error] = t(:error)
      render 'edit'
    end
  end

  def destroy
    if @question.destroy
      flash[:success] = t(:question_deleted)
    else
      flash[:error] = t(:error)
    end
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question!
    @question = Question.find params[:id]
  end
end

app/views/questions/_form.html.erb
    <%= render "shared/errors", object: @question %>

    <%= form_with model: @question do |f| %>
        <div class="form-group">
            <%= f.label :Title, "Title" %>
            <%= f.text_field :title, :class => 'form-control', required: true, minlength: 2, placeholder: "Title" %>
        </div>

        <div class="form-group">
            <%= f.label :Body, "Body" %>
            <%= f.text_area :body, :class => 'form-control' %>
        </div>

        <%= f.submit :class => 'btn btn-primary mt-2' %>
    <% end %>

app/views/questions/edit.html.erb
 
    <% provide :page_title, "Edit question" %>
    <% currently_at "Questions" %>

    <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Edit question</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <%= button_to "Back", questions_path, :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
            </div>
        </div>
    </div>

    <%= render "form" %>

app/views/questions/index.html.erb
    <% provide :page_title, "Questions" %>
    <% currently_at "Questions" %>

    <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Questions</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <%= button_to "New question", new_question_path, :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
            </div>
        </div>
    </div>

    <%= render "shared/flash" %>

    <%== pagination @pagy %>

    <div class="row">
        <% @questions.each do |question| %>
            <div class="col-sm-4">
                <div class="card mt-4">
                    <div class="card-body">
                        <h5 class="card-title"><%=question.title %></h5>
                        <p class="card-text"><%= truncate strip_tags(question.body),length: 125, omission: "... (continued)" %></p>
                        <p class="card-text"><small class="text-muted">Created: <%= question.formatted_created_at %></small></p>
                        <div class="btn-group">
                            <%= nav_tab "Show", question_path(question), :method => "get", :class => 'btn btn-sm btn-outline-primary' %>
                            <%= nav_tab "Edit", edit_question_path(question), :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
                            <%= nav_tab "Delete", question_path(question), :method => "delete", :class => 'btn btn-sm btn-outline-danger', form: {data: {confirm: "Are you sure?"}} %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>

    <%== pagination @pagy %>

app/views/questions/new.html.erb
    <% provide :page_title, "New Question" %>
    <% currently_at "Questions" %>

    <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">New question</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <%= button_to "Back", questions_path, :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
            </div>
        </div>
    </div>

    <%= render "form" %>

app/views/questions/show.html.erb
    <% provide :page_title, "Question" %>
    <% currently_at "Questions" %>

    <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h5">Question</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <%= nav_tab "Edit", edit_question_path(@question), :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
                <%= nav_tab "Delete", question_path(@question), :method => "delete", :class => 'btn btn-sm btn-outline-danger', form: {data: {confirm: "Are you sure?"}} %>
                <%= nav_tab "Back", questions_path, :method => "get", :class => 'btn btn-sm btn-outline-dark' %>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title"><%=@question.title %></h5>
            <p class="card-text"><%= sanitize @question.body %></p>
            <p class="card-text"><small class="text-muted">Created: <%= @question.formatted_created_at %></small></p>
        </div>
    </div>


    <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h5">Answer</h1>
    </div>

    <%= render "answers/form" %>

    <% if @answers.any? %>
        <div class="card my-3">
            <ul class="list-group list-group-flush">
                <%= render partial: "answers/answer", collection: @answers, as: :answer, locals: {question: @question} %>
            </ul>
        </div>
    <% end %>

    <%= pagination @pagy %>
    