config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resources :questions, only: [:index, :new, :edit, :create]
  # resources :questions, only: %i[index new edit create update destroy show]
  # get "/questions", to: "questions#index"
  # get "/questions/new", to: "questions#new"
  # post "/questions", to: "questions#create"
  # get "/questions/:id/edit", to: "questions#edit"

  resource :session, only: %i[new create destroy]
  resources :users, only: %i[index new create edit update destroy]
  resources :customers, only: %i[index new create edit update destroy]

  resources :tool_categories do
    resources :tool_lists
  end

  resources :tool_lists do
    resources :tool_numbers
  end

  # scope 'tool', as: 'tool' do
  #   resources :tool_categories, as: 'category', path: 'category' do
  #     resources :tool_lists, as: 'list', path: 'list' do
  #       resources :tool_numbers, as: 'number', path: 'number'
  #     end
  #   end
  # end

  get '/tool_lists/preview', to: 'tool_lists#preview'

  resources :questions do
    # resources :answers, only: %i[create destroy edit update]
    resources :answers, except: %i[new show]
  end

  root 'pages#index'
end

app/models/tool_list.rb
# frozen_string_literal: true

class ToolList < ApplicationRecord
  belongs_to :tool_category
  has_many :tool_numbers, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/tool_lists_controller.rb
# frozen_string_literal: true

class ToolListsController < ApplicationController
  before_action :set_tool_list!, only: %i[show edit update destroy]

  def index
    @pagy, @tool_lists = pagy ToolList.order(name: :asc)

    @tool_lists = ToolList.all
    respond_to do |format|
      format.html
      format.pdf do
        pdf = OrderPdf.new(@tool_lists)
        send_data(pdf.render, filename: 'tools_list.pdf', type: 'application/pdf', disposition: 'inline')
      end
    end
  end

  def show
    @tool_number = @tool_list.tool_numbers.build
    @pagy, @tool_numbers = pagy @tool_list.tool_numbers.order(number: :desc)
  end

  def new
    @tool_list = ToolList.new
  end

  def edit; end

  def create
    @tool_list = ToolList.new tool_list_params
    @tool_category = @tool_list.tool_category

    if @tool_list.save
      flash[:success] = t(:tool_list_created)
      redirect_to tool_category_path(@tool_category)
    else
      flash[:error] = t(:error)
      render :new
    end
  end

  def update
    if @tool_list.update tool_list_params
      flash[:success] = t(:tool_list_updated)
      redirect_to tool_lists_path
    else
      flash[:error] = t(:error)
      render 'edit'
    end
  end

  def destroy
    if @tool_list.destroy
      flash[:success] = t(:tool_list_deleted)
    else
      flash[:error] = t(:error)
    end
    redirect_to tool_lists_path
  end

  private

  def tool_list_params
    params.require(:tool_list).permit(:name, :body, :tool_category_id)
  end

  def set_tool_list!
    @tool_list = ToolList.find params[:id]
  end
end

app/helpers/tool_lists_helper.rb
# frozen_string_literal: true

module ToolListsHelper
end

app/views/tool_lists/_form.html.erb
<%= render "shared/errors", object: @tool_list %>

<%= form_with model: @tool_list do |f| %>
    <div class="form-group">
        <%= f.label :Name, "Name" %>
        <%= f.text_field :name, :class => 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :Body, "Body" %>
        <%= f.text_area :body, :class => 'form-control' %>
    </div>

    <div class="form-group" aria-label="Select tool group">
        <%= f.select :tool_category_id, ToolCategory.pluck(:name, :id), {}, { :class => 'form-select' } %>
    </div>    

    <%= f.submit "Submit", :class => 'form-control', disable_with: 'Submiting...' %>

<% end %>

app/views/tool_lists/edit.html.erb
 
    <% provide :page_title, "Edit tool" %>
    <% currently_at "Tools" %>

    <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Tool list edit</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <%= button_to "Back", tool_list_path, :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
            </div>
        </div>
    </div>

    <%= render "form" %>

app/views/tool_lists/index.html.erb
    <% provide :page_title, "Tool lists" %>
    <% currently_at "Tool lists" %>

    <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Tool lists index</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <%= button_to "New tool list", new_tool_list_path, :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
                <%= button_to "View as PDF", tool_lists_path(@tool_list, format: "pdf"), form: {target: '_blank'}, :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
            </div>
        </div>
    </div>

    <%= render "shared/flash" %>

    <%== pagination @pagy %>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Category</th>
                <th scope="col">Total</th>
                <th scope="col">Inrent</th>
                <th scope="col">Broken</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @tool_lists.each do |tool_list| %>
            <tr>
                <td><%= tool_list.id %></td>
                <td><%= link_to tool_list.name, tool_list_path(tool_list) %></td>
                <td><%= tool_list.tool_category.name %></td>
                <td><%= tool_list.tool_numbers.count %></td>
                <td> inrent </td>
                <td> broken </td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <%= nav_tab "Show", tool_list_path(tool_list), :method => "get", :class => 'btn btn-sm btn-outline-primary' %>
                        <%= nav_tab "Edit", edit_tool_list_path(tool_list), :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
                        <%= nav_tab "Delete", tool_list_path(tool_list), :method => "delete", :class => 'btn btn-sm btn-outline-danger', form: {data: {confirm: "Are you sure?"}} %>
                    </div>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>

app/views/tool_lists/new.html.erb
    <% provide :page_title, "New Tool" %>
    <% currently_at "Tools" %>

    <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Tool list new</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <%= button_to "Back", tool_lists_path, :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
            </div>
        </div>
    </div>

    <%= render "form" %>

app/views/tool_lists/show.html.erb
    <% provide :page_title, "Tool number" %>
    <% currently_at "Tools" %>

    <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Tool list show</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <%= button_to "New number", new_tool_list_tool_number_path(@tool_list), :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
                <%= button_to "Back", tool_lists_path, :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
            </div>
        </div>
    </div>

    <%= render "shared/flash" %>

    <%= form_with :class => "form row my-3", model: [@tool_list, @tool_number] do |f| %>
        <div class="col-3">
            <%= f.text_field :number, :class => 'form-control' %>
        </div>
        <div class="col">
            <%= f.submit 'New number', :class => 'btn btn-secondary' %>
        </div>
    <% end %>




    <div class="card my-3">
        <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Name</th>
                <th scope="col">Status</th>
                <th scope="col">Work hours</th>
                <th scope="col">Rent count</th>
                <th scope="col">Notes</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            <%= render partial: "tool_numbers/tool", collection: @tool_numbers, as: :tool_number, locals: {tool_list: @tool_list} %>
            </tbody>
        </table>
    </div>
    </div>