config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resources :questions, only: [:index, :new, :edit, :create]
  # resources :questions, only: %i[index new edit create update destroy show]
  # get "/questions", to: "questions#index"
  # get "/questions/new", to: "questions#new"
  # post "/questions", to: "questions#create"
  # get "/questions/:id/edit", to: "questions#edit"

  resource :session, only: %i[new create destroy]
  resources :users, only: %i[index new create edit update destroy]
  resources :customers, only: %i[index new create edit update destroy]

  resources :tool_categories do
    resources :tool_lists
  end

  resources :tool_lists do
    resources :tool_numbers
  end

  # scope 'tool', as: 'tool' do
  #   resources :tool_categories, as: 'category', path: 'category' do
  #     resources :tool_lists, as: 'list', path: 'list' do
  #       resources :tool_numbers, as: 'number', path: 'number'
  #     end
  #   end
  # end

  get '/tool_lists/preview', to: 'tool_lists#preview'

  resources :questions do
    # resources :answers, only: %i[create destroy edit update]
    resources :answers, except: %i[new show]
  end

  root 'pages#index'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true, length: { minimum: 5 }

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :customer
  belongs_to :tool_number
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  belongs_to :user, optional: true
  validates :user_id, uniqueness: true, if: -> { user_id.present? }
  has_many :contracts
  has_many :tool_numbers, through: :contracts
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :answers, dependent: :destroy

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }
end

app/models/tool_category.rb
# frozen_string_literal: true

class ToolCategory < ApplicationRecord
  has_many :tool_list, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/tool_list.rb
# frozen_string_literal: true

class ToolList < ApplicationRecord
  belongs_to :tool_category
  has_many :tool_numbers, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/tool_number.rb
# frozen_string_literal: true

class ToolNumber < ApplicationRecord
  belongs_to :tool_list

  has_and_belongs_to_many :contracts
  has_many :customers, through: :contracts

  validates :number, presence: true, numericality: true, uniqueness: { scope: :tool_list }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :old_password
  has_one :customer
  has_secure_password validations: false

  validate :password_presence
  validate :correct_old_password, on: :update, if: -> { password.present? }
  validates :password, confirmation: true, allow_blank: true,
            length: {minimum:8, maximum:70}

  validates :email, presence: true, uniqueness: true, 'valid_email_2/email': true

  validates :username, presence: true, uniqueness: true

  validate :password_complexity

  private

  def correct_old_password
    return if BCrypt::Password.new(password_digest_was).is_password?(old_password)

    errors.add :old_password, 'is incorect'
  end

  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}/

    errors.add :password, 'complexity requirement not met. Minimum eight characters and at least one letter and one number'
  end

  def password_presence
    errors.add(:password, :blank) unless password_digest.present?
  end
  
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :set_question!
  # before_action :set_answer!, only: %i[edit update destroy]
  before_action :set_answer!, except: :create

  def edit; end

  def create
    @answer = @question.answers.build answer_params

    if @answer.save
      flash[:success] = t(:answer_created)
      redirect_to question_path(@question)
    else
      @question = @question.decorate
      @answers = @question.answers.order created_at: :desc
      @answers = @answers.decorate
      render 'questions/show'
    end
  end

  def update
    if @answer.update answer_params
      flash[:success] = t(:answer_updated)
      redirect_to question_path(@question, anchor: dom_id(@answer))
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    flash[:success] = t(:answer_deleted)
    redirect_to question_path(@question)
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find params[:question_id]
  end

  def set_answer!
    @answer = @question.answers.find params[:id]
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_no_authentication, only: %i[new create]
    before_action :require_authentication, only: %i[destroy]

    def new
    end

    def create
        user = User.find_by email: params[:email]
        if user&.authenticate(params[:password])
            sign_in user
            flash[:success] = "Welcome back, #{current_user.name_or_email}! You have successfully logged in"
            redirect_to root_path
        else
            flash[:error] = "That email or password is incorrect."
            redirect_to new_session_path
        end
    end

    def destroy
        sign_out
        flash[:success] = "You have successfully logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user!, only: %i[edit update destroy]
  before_action :require_no_authentication, only: %i[new create]
  before_action :require_authentication, only: %i[edit update destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new user_params
    if @user.save
      sign_in @user
      flash[:success] = t(:user_created)
      redirect_to users_path
    else
      flash[:error] = t(:error)
      render :new
    end
  end

  def update
    if @user.update user_params
      flash[:success] = t(:user_updated)
      redirect_to users_path
    else
      flash[:error] = t(:error)
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:success] = t(:user_deleted)
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_comfirmation, :old_password, :new_password)
  end

  def set_user!
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend

  def pagination(obj)
    # rubocop:disable Rails/OutputSafety
    raw(pagy_bootstrap_nav(obj)) if obj.pages > 1
    # rubocop:enable Rails/OutputSafety
  end

  def nav_tab(title, url, options = {})
    current_page = options.delete :current_page
    css_class = current_page == title ? 'active' : ''

    options[:class] = if options[:class]
                        "#{options[:class]} #{css_class}"
                      else
                        css_class
                      end

    link_to title, url, options
  end

  def currently_at(current_page = '')
    render partial: 'shared/sidebar_menu', locals: { current_page: current_page }
  end

  def full_title(page_title = '')
    base_title = 'Plank'
    if page_title.present?
      "#{page_title} | #{base_title} "
    else
      base_title
    end
  end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/customers_helper.rb
# frozen_string_literal: true

module CustomersHelper
end

app/helpers/tool_categories_helper.rb
# frozen_string_literal: true

module ToolCategoriesHelper
end

app/helpers/tool_lists_helper.rb
# frozen_string_literal: true

module ToolListsHelper
end

app/helpers/tool_numbers_helper.rb
# frozen_string_literal: true

module ToolNumbersHelper
end

app/helpers/tools_helper.rb
# frozen_string_literal: true

module ToolsHelper
end

app/views/shared/_errors.html.erb
    <% if object.errors.full_messages.any? %>
        <div class="alert alert-danger" role="alert">
            <ul class="mb-0">
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
            <ul>
        </div>
    <% end %>

app/views/shared/_flash.html.erb
    <% if flash.any? %>
        <% flash.each do |k,v| %>
            <%= tag.div v, class: "alert alert-#{k}", role: 'alert' %>
        <% end %>
    <% end %>

app/views/shared/_menu.html.erb
    <%= provide :main_menu do %>
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3 sidebar-sticky">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <%= nav_tab 'Dashboard', root_path, class: 'nav-link bi bi-house', current_page: current_page %>
                </li>
                <li class="nav-item">
                    <%= nav_tab 'Questions', questions_path, class: 'nav-link bi bi-question-circle', current_page: current_page %>
                </li>
                <li class="nav-item">
                    <%= nav_tab 'Tool lists', tool_lists_path, class: 'nav-link bi bi-hammer', current_page: current_page %>
                </li>
                <li class="nav-item">
                    <%= nav_tab 'Tool categories', tool_categories_path, class: 'nav-link bi bi-wrench-adjustable-circle', current_page: current_page %>
                </li>
                <li class="nav-item">
                    <%= nav_tab 'Users', users_path, class: 'nav-link bi bi-person', current_page: current_page %>
                </li>  
                <li class="nav-item">
                    <%= nav_tab 'Customers', customers_path, class: 'nav-link bi bi-person-square', current_page: current_page %>
                </li>
                <li class="nav-item">
                    <%= nav_tab 'Sign Up', new_user_path, class: 'nav-link bi bi-box-arrow-in-right', current_page: current_page %>
                </li>                
            </ul>
        </div>
        </nav>
    <% end %>

app/views/shared/_sidebar_menu.html.erb
    <%= provide :sidebar_menu do %>
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3 sidebar-sticky">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <%= nav_tab 'Dashboard', root_path, class: 'nav-link bi bi-house', current_page: current_page %>
                </li>
                <li class="nav-item">
                    <%= nav_tab 'Questions', questions_path, class: 'nav-link bi bi-question-circle', current_page: current_page %>
                </li>
                <li class="nav-item">
                    <%= nav_tab 'Tool lists', tool_lists_path, class: 'nav-link bi bi-hammer', current_page: current_page %>
                </li>
                <li class="nav-item">
                    <%= nav_tab 'Tool categories', tool_categories_path, class: 'nav-link bi bi-wrench-adjustable-circle', current_page: current_page %>
                </li>
                <li class="nav-item">
                    <%= nav_tab 'Users', users_path, class: 'nav-link bi bi-person', current_page: current_page %>
                </li>  
                <li class="nav-item">
                    <%= nav_tab 'Customers', customers_path, class: 'nav-link bi bi-person-square', current_page: current_page %>
                </li>
                <li class="nav-item">
                    <%= nav_tab 'Sign Up', new_user_path, class: 'nav-link bi bi-box-arrow-in-right', current_page: current_page %>
                </li>                
            </ul>
        </div>
        </nav>
    <% end %>

app/views/tool_variants/_form.html.erb
    <%= render "shared/flash" %>
    <%= render "shared/errors", object: @tool_variant %>

    <%= form_with :class => "my-3", model: [@tool, @tool_variant] do |f| %>
        <div class="form-group">
            <%= f.label :tool_number %>
            <%= f.text_field :tool_number, :class => 'form-control' %>
            <%= f.label :body %>
            <%= f.text_field :body, :class => 'form-control' %>
        </div>

        <%= f.submit :class => 'btn btn-primary mt-2' %>
    <% end %>

app/views/tool_variants/new.html.erb
    <% provide :page_title, "New tool variant" %>
    <% currently_at "Tools" %>

    <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">New tool variant</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
            </div>
        </div>
    </div>

<%= render "form" %>

app/views/tool_variants/show.html.erb
    <% provide :page_title, "Tools" %>
    <% currently_at "Tools variant show" %>

    <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h5"><%= @tool_variant.tool_number %> - <%=@tool.name %></h1>
    </div>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title"><%=@tool.name %></h5>
            <p class="card-text"><%= @tool_variant.tool_number %></p>
            <p class="card-text"><%= @tool_variant.body %></p>
        </div>
    </div>