config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # resources :questions, only: [:index, :new, :edit, :create]
  # resources :questions, only: %i[index new edit create update destroy show]
  # get "/questions", to: "questions#index"
  # get "/questions/new", to: "questions#new"
  # post "/questions", to: "questions#create"
  # get "/questions/:id/edit", to: "questions#edit"

  resource :session, only: %i[new create destroy]
  resources :users, only: %i[index new create edit update destroy]
  resources :customers, only: %i[index new create edit update destroy]

  resources :tool_categories do
    resources :tool_lists
  end

  resources :tool_lists do
    resources :tool_numbers
  end

  # scope 'tool', as: 'tool' do
  #   resources :tool_categories, as: 'category', path: 'category' do
  #     resources :tool_lists, as: 'list', path: 'list' do
  #       resources :tool_numbers, as: 'number', path: 'number'
  #     end
  #   end
  # end

  get '/tool_lists/preview', to: 'tool_lists#preview'

  resources :questions do
    # resources :answers, only: %i[create destroy edit update]
    resources :answers, except: %i[new show]
  end

  root 'pages#index'
end

app/models/tool_category.rb
# frozen_string_literal: true

class ToolCategory < ApplicationRecord
  has_many :tool_list, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/tool_categories_controller.rb
# frozen_string_literal: true

class ToolCategoriesController < ApplicationController
  before_action :set_tool_category!, only: %i[show edit update destroy]

  def index
    @pagy, @tool_categories = pagy ToolCategory.order(name: :asc)

    @tool_categories = ToolCategory.all
    respond_to do |format|
      format.html
      format.pdf do
        pdf = OrderPdf.new(@tool_categories)
        send_data(pdf.render, filename: 'tools_category.pdf', type: 'application/pdf', disposition: 'inline')
      end
    end
  end

  def show
    @tool_list = @tool_category.tool_list.build
    @pagy, @tool_lists = pagy @tool_category.tool_list.order(number: :desc)
  end

  def new
    @tool_category = ToolCategory.new
  end

  def edit; end

  def create
    @tool_category = ToolCategory.new tool_category_params
    if @tool_category.save
      flash[:success] = t(:tool_category_created)
      redirect_to tool_categories_path
    else
      flash[:error] = t(:error)
      render :new
    end
  end

  def update
    if @tool_category.update tool_category_params
      flash[:success] = t(:tool_category_updated)
      redirect_to tool_categories_path
    else
      flash[:error] = t(:error)
      render 'edit'
    end
  end

  def destroy
    if @tool_category.destroy
      flash[:success] = t(:tool_category_deleted)
    else
      flash[:error] = t(:error)
    end
    redirect_to tool_categories_path
  end

  private

  def tool_category_params
    params.require(:tool_category).permit(:name, :description)
  end

  def set_tool_category!
    @tool_category = ToolCategory.find params[:id]
  end
end

app/helpers/tool_categories_helper.rb
# frozen_string_literal: true

module ToolCategoriesHelper
end

app/views/tool_categories/_form.html.erb
<%= render "shared/errors", object: @tool_category %>

<%= form_with model: @tool_category do |f| %>
    <div class="form-group">
        <%= f.label :Name, "Name" %>
        <%= f.text_field :name, :class => 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :Description, "Description" %>
        <%= f.text_area :description, :class => 'form-control' %>
    </div>

    <%= f.submit "Submit", :class => 'form-control', disable_with: 'Submiting...' %>

<% end %>

app/views/tool_categories/_tool.html.erb
            <tr>
                <td><%= tool_list.name %></td>
                <td><%= tool_category.name %></td>
                <td><%= tool_list.tool_numbers.count %></td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <%= nav_tab "Show", tool_category_tool_list_path(tool_category, tool_list), :method => "get", :class => 'btn btn-sm btn-outline-primary' %>
                        <%= nav_tab "Edit", edit_tool_category_tool_list_path(tool_category, tool_list), :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
                        <%= nav_tab "Delete", tool_category_tool_list_path(tool_category, tool_list), :method => "delete", :class => 'btn btn-sm btn-outline-danger', form: {data: {confirm: "Are you sure?"}} %>
                    </div>
                </td>
            </tr>

app/views/tool_categories/edit.html.erb
 
    <% provide :page_title, "Edit tool" %>
    <% currently_at "Tools" %>

    <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Tool category edit</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <%= button_to "Back", tool_list_path, :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
            </div>
        </div>
    </div>

    <%= render "shared/flash" %>

    <%= render "form" %>

app/views/tool_categories/index.html.erb
    <% provide :page_title, "Tool categories" %>
    <% currently_at "Tool categories" %>

    <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Tool categories index</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <%= button_to "New tool category", new_tool_category_path, :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
            </div>
        </div>
    </div>

    <%= render "shared/flash" %>

    <%== pagination @pagy %>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Lists</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @tool_categories.each do |tool_category| %>
            <tr>
                <td><%= tool_category.id %></td>
                <td><%= link_to tool_category.name, tool_category_path(tool_category) %></td>
                <td><%= tool_category.description %></td>
                <td><%= tool_category.tool_list.count %></td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <%= nav_tab "Show", tool_category_path(tool_category), :method => "get", :class => 'btn btn-sm btn-outline-primary' %>
                        <%= nav_tab "Edit", edit_tool_category_path(tool_category), :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
                        <%= nav_tab "Delete", tool_category_path(tool_category), :method => "delete", :class => 'btn btn-sm btn-outline-danger', form: {data: {confirm: "Are you sure?"}} %>
                    </div>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>

app/views/tool_categories/new.html.erb
    <% provide :page_title, "New tool category" %>
    <% currently_at "Tools" %>

    <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Tool category new</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <%= button_to "Back", tool_categories_path, :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
            </div>
        </div>
    </div>

    <%= render "shared/flash" %>

    <%= render "form" %>

app/views/tool_categories/show.html.erb
    <% provide :page_title, "Tool category list" %>
    <% currently_at "Tools" %>

    <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Tool category show</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <%= button_to "New list", new_tool_list_path(@tool_list), :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
                <%= button_to "Back", tool_categories_path, :method => "get", :class => 'btn btn-sm btn-outline-secondary' %>
            </div>
        </div>
    </div>

    <%= render "shared/flash" %>

    <div class="card my-3">
        <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th scope="col">Tool lists</th>
                <th scope="col">Category</th>
                <th scope="col">Numbers</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            <%= render partial: "tool", collection: @tool_lists, as: :tool_list, locals: {tool_category: @tool_category} %>
            </tbody>
        </table>
    </div>
    </div>